import type { CollectionConfig } from 'payload'

import {
  BlocksFeature,
  FixedToolbarFeature,
  HeadingFeature,
  HorizontalRuleFeature,
  InlineToolbarFeature,
  lexicalEditor,
} from '@payloadcms/richtext-lexical'

import { authenticated } from '../../access/authenticated'
import { authenticatedOrPublished } from '../../access/authenticatedOrPublished'
import { Banner } from '../../blocks/Banner/config'
import { Code } from '../../blocks/Code/config'
import { MediaBlock } from '../../blocks/MediaBlock/config'
import { revalidateDelete, revalidateArticle } from './hooks/revalidateArticle'
import { slugField } from 'payload'

import {
  MetaDescriptionField,
  MetaImageField,
  MetaTitleField,
  OverviewField,
  PreviewField,
} from '@payloadcms/plugin-seo/fields'

export const Articles: CollectionConfig = {
  slug: 'articles',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'authorName', 'channel', 'publishedAt', '_status'],
    group: 'المحتوى',
  },
  defaultPopulate: {
    title: true,
    slug: true,
    excerpt: true,
    heroImage: true,
    authorName: true,
    publishedAt: true,
    categories: true,
    channel: true,
  },
  access: {
    create: authenticated,
    delete: authenticated,
    read: authenticatedOrPublished,
    update: authenticated,
  },
  fields: [
    {
      name: 'title',
      label: 'العنوان',
      type: 'text',
      required: true,
    },
    {
      type: 'tabs',
      tabs: [
        {
          label: 'المحتوى',
          fields: [
            {
              name: 'heroImage',
              label: 'الصورة الرئيسية',
              type: 'upload',
              relationTo: 'media',
            },
            {
              name: 'excerpt',
              label: 'ملخص المقال',
              type: 'textarea',
              required: true,
              admin: {
                description: 'نبذة مختصرة عن المقال تظهر في القوائم',
              },
            },
            {
              name: 'content',
              label: 'المحتوى',
              type: 'richText',
              editor: lexicalEditor({
                features: ({ rootFeatures }) => {
                  return [
                    ...rootFeatures,
                    HeadingFeature({ enabledHeadingSizes: ['h1', 'h2', 'h3', 'h4'] }),
                    BlocksFeature({ blocks: [Banner, Code, MediaBlock] }),
                    FixedToolbarFeature(),
                    InlineToolbarFeature(),
                    HorizontalRuleFeature(),
                  ]
                },
              }),
              required: true,
            },
          ],
        },
        {
          label: 'المصدر',
          fields: [
            {
              name: 'sourceVideo',
              label: 'الفيديو المصدر',
              type: 'relationship',
              relationTo: 'videos',
              admin: {
                description: 'الفيديو الذي تم استخلاص المقال منه',
              },
            },
            {
              name: 'channel',
              label: 'القناة',
              type: 'relationship',
              relationTo: 'channels',
            },
            {
              name: 'youtubeUrl',
              label: 'رابط يوتيوب',
              type: 'text',
              admin: {
                description: 'الرابط المباشر للفيديو على يوتيوب',
              },
            },
            {
              name: 'isAutoGenerated',
              label: 'مقال مولد تلقائياً',
              type: 'checkbox',
              defaultValue: false,
              admin: {
                readOnly: true,
              },
            },
          ],
        },
        {
          label: 'التصنيف',
          fields: [
            {
              name: 'categories',
              label: 'التصنيفات',
              type: 'relationship',
              relationTo: 'categories',
              hasMany: true,
              admin: {
                position: 'sidebar',
              },
            },
            {
              name: 'relatedArticles',
              label: 'مقالات ذات صلة',
              type: 'relationship',
              relationTo: 'articles',
              hasMany: true,
              filterOptions: ({ id }) => ({
                id: { not_in: [id] },
              }),
            },
            {
              name: 'tags',
              label: 'الوسوم',
              type: 'array',
              fields: [
                {
                  name: 'tag',
                  label: 'وسم',
                  type: 'text',
                },
              ],
            },
          ],
        },
        {
          name: 'meta',
          label: 'SEO',
          fields: [
            OverviewField({
              titlePath: 'meta.title',
              descriptionPath: 'meta.description',
              imagePath: 'meta.image',
            }),
            MetaTitleField({
              hasGenerateFn: true,
            }),
            MetaImageField({
              relationTo: 'media',
            }),
            MetaDescriptionField({}),
            PreviewField({
              hasGenerateFn: true,
              titlePath: 'meta.title',
              descriptionPath: 'meta.description',
            }),
          ],
        },
      ],
    },
    {
      name: 'authorName',
      label: 'اسم الكاتب',
      type: 'text',
      required: true,
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'publishedAt',
      label: 'تاريخ النشر',
      type: 'date',
      required: true,
      admin: {
        position: 'sidebar',
        date: {
          pickerAppearance: 'dayAndTime',
        },
      },
      hooks: {
        beforeChange: [
          ({ siblingData, value }) => {
            if (siblingData._status === 'published' && !value) {
              return new Date()
            }
            return value
          },
        ],
      },
    },
    {
      name: 'featured',
      label: 'مقال مميز',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        position: 'sidebar',
        description: 'يظهر في القسم الرئيسي بالصفحة الأولى',
      },
    },
    {
      name: 'breakingNews',
      label: 'خبر عاجل',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        position: 'sidebar',
      },
    },
    slugField(),
  ],
  hooks: {
    afterChange: [revalidateArticle],
    afterDelete: [revalidateDelete],
  },
  versions: {
    drafts: {
      autosave: {
        interval: 100,
      },
      schedulePublish: true,
    },
    maxPerDoc: 50,
  },
}
